.class public final Lasj;
.super Laqf;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "<R::",
        "Laql;",
        ">",
        "Laqf",
        "<TR;>;"
    }
.end annotation


# instance fields
.field private final a:Laqu;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Laqu",
            "<TR;>;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>(Laqg;)V
    .locals 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Laqg",
            "<TR;>;)V"
        }
    .end annotation

    invoke-direct {p0}, Laqf;-><init>()V

    instance-of v0, p1, Laqu;

    if-nez v0, :cond_0

    new-instance v0, Ljava/lang/IllegalArgumentException;

    const-string v1, "OptionalPendingResult can only wrap PendingResults generated by an API call."

    invoke-direct {v0, v1}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v0

    :cond_0
    check-cast p1, Laqu;

    iput-object p1, p0, Lasj;->a:Laqu;

    return-void
.end method


# virtual methods
.method public a(JLjava/util/concurrent/TimeUnit;)Laql;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(J",
            "Ljava/util/concurrent/TimeUnit;",
            ")TR;"
        }
    .end annotation

    iget-object v0, p0, Lasj;->a:Laqu;

    invoke-virtual {v0, p1, p2, p3}, Laqu;->a(JLjava/util/concurrent/TimeUnit;)Laql;

    move-result-object v0

    return-object v0
.end method

.method public a(Laqm;)V
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Laqm",
            "<-TR;>;)V"
        }
    .end annotation

    iget-object v0, p0, Lasj;->a:Laqu;

    invoke-virtual {v0, p1}, Laqu;->a(Laqm;)V

    return-void
.end method

.method public a(Laqm;JLjava/util/concurrent/TimeUnit;)V
    .locals 2
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Laqm",
            "<-TR;>;J",
            "Ljava/util/concurrent/TimeUnit;",
            ")V"
        }
    .end annotation

    iget-object v0, p0, Lasj;->a:Laqu;

    invoke-virtual {v0, p1, p2, p3, p4}, Laqu;->a(Laqm;JLjava/util/concurrent/TimeUnit;)V

    return-void
.end method

.method public a()Z
    .locals 1

    iget-object v0, p0, Lasj;->a:Laqu;

    invoke-virtual {v0}, Laqu;->e()Z

    move-result v0

    return v0
.end method

.method public b()Laql;
    .locals 3
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()TR;"
        }
    .end annotation

    invoke-virtual {p0}, Lasj;->a()Z

    move-result v0

    if-eqz v0, :cond_0

    const-wide/16 v0, 0x0

    sget-object v2, Ljava/util/concurrent/TimeUnit;->MILLISECONDS:Ljava/util/concurrent/TimeUnit;

    invoke-virtual {p0, v0, v1, v2}, Lasj;->a(JLjava/util/concurrent/TimeUnit;)Laql;

    move-result-object v0

    return-object v0

    :cond_0
    new-instance v0, Ljava/lang/IllegalStateException;

    const-string v1, "Result is not available. Check that isDone() returns true before calling get()."

    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    throw v0
.end method

.method public c()Ljava/lang/Integer;
    .locals 1

    iget-object v0, p0, Lasj;->a:Laqu;

    invoke-virtual {v0}, Laqu;->c()Ljava/lang/Integer;

    move-result-object v0

    return-object v0
.end method
